// ✅ Technologies you know (simple list)
export const MySkill = [
  "Flutter",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vue",
  "Angular",
  "Node.js",
  ".NET",
  "Laravel",
  "Python",
  "MySQL",
  "SQL Server",
  "PostgreSQL",
  "Docker",
  "Kubernetes",
  "Nginx",
  "AWS",
  "Digital Ocean",
];

export const skills = [
  { name: "JavaScript / TypeScript", level: 90 },
  { name: "React / Next.js", level: 90 },
  { name: "Vue / Angular", level: 80 },
  { name: "Node.js / Express", level: 85 },
  { name: ".NET / Laravel", level: 85 },
  { name: "Python (API & ML)", level: 50 },
  { name: "Database Design & SQL", level: 75 },
  { name: "PostgreSQL / MySQL / SQL Server", level: 50 },
  { name: "Cloud Architecture (AWS, Digital Ocean)", level: 90 },
  { name: "DevOps (CI/CD, Docker, Kubernetes)", level: 20 },
  { name: "Nginx / Reverse Proxy", level: 78 },
  { name: "Machine Learning / AI", level: 30 },
];
